Redesign Timing and Spacing tool
Tumo-Product/timing-and-spacing pull request #1
Opened 2022-05-16 08:44 UTC by vrezhMik

Change UI view of tool. Separated select and deselect buttons.
Connected play and pause buttons. Change initial view to have a start button
and not autoplay the animation. Add function which autocheks the students answer.
Student will be able to submit only if all correct frames are selected.

2022-05-16 15:31 UTC, tumochristine requested changes
Excellent work Vrezh! You did a great job of adding a new feature to legacy code. 

I noticed a few bugs:
1) Exporting isn't working for me
2) The photos in the tutorial popup aren't loading 
![Screen Shot 2022-05-16 at 7 24 14 PM](https://user-images.githubusercontent.com/102517998/168628945-d49e6671-6597-4eaf-ad0f-873c4aefdcd1.png)

3) There is content that is going outside the borders on my screen 
![Screen Shot 2022-05-16 at 7 22 58 PM](https://user-images.githubusercontent.com/102517998/168629033-4d2bf5c7-6a82-42b2-8677-7317ed51f070.png)

I also need to test the importing functionality tomorrow.

Great work!

2022-05-16 15:31 UTC, tumochristine commented on src/ui_manager.js
> +    document.getElementById("playBtn").style.pointerEvents = "none";
Why do we need to set all these pointerEvents to none?

2022-05-16 15:31 UTC, tumochristine commented on src/ui_manager.js
> +    this.infoBtn.onclick = this.btnInfo;
can we change`btnInfo` to be a verb, like `handleInfoClick` or `openInfoModal`?

2022-05-16 15:31 UTC, tumochristine commented on src/ui_manager.js
> +    this.closeInfoBtn.onclick = this.btnCloseInfo;
same comment for `btnCloseInfo`

2022-05-16 15:31 UTC, tumochristine commented on index.html
> +                <ul id="contentList"></ul>
what do `infoContRow` and `contentList` have in them? Can we clarify the names a bit?

2022-05-16 15:31 UTC, tumochristine commented on src/ui_manager.js
> +  selectedFrames: [1, 8, 13, 18, 22, 25, 27, 29, 48],
I am getting a bug where if I just click one answer and try to submit, it calls `checkTheAnswer` with an input of a huge array. I think it's because `selectedFrames` isn't initially empty, when it should be.

2022-05-16 15:31 UTC, tumochristine commented on src/ui_manager.js
> +  presentData: function (content) {
This adds the tutorial content in the correct language to the popup, right? Can we rename it to be a bit more descriptive?

2022-05-16 15:31 UTC, tumochristine commented on src/ui_manager.js
> +  return true;
It's generally bad practice to mutate an argument. We can rewrite this function as:

```
const sortedArray = arr.slice().sort((a, b) => a - b);
return (sortedArray.length === UIManager.correctFrames.length) && (UIManager.correctFrames.every((val, index) => val === sortedArray[index]));
```

2022-05-17 06:11 UTC, vrezhMik commented on examiner.html
> +    <title>Document</title>
done

2022-05-17 06:22 UTC, vrezhMik commented on index.html
> +                <div class="scale" id="scale"></div>
Yes, it uses in style.css:316

2022-05-17 13:22 UTC, vrezhMik commented on index.html
> +            <canvas id="alt_canv" width="1920" height="1080"> </canvas>
done

2022-05-17 13:23 UTC, vrezhMik commented on src/ui_manager.js
> +    this.closeInfoBtn.onclick = this.btnCloseInfo;
done

2022-05-17 13:24 UTC, vrezhMik commented on index.html
> +          <div class="canvs">
done

2022-05-17 13:24 UTC, vrezhMik commented on index.html
> +                  list="ticks1"
done

2022-05-18 07:25 UTC, vrezhMik commented on index.html
> +                <div id="infoBtnRowBg"></div>
done

2022-05-18 07:25 UTC, vrezhMik commented on index.html
> +            <div id="infoCont">
done

2022-05-18 07:29 UTC, vrezhMik commented on src/anim.js
> +  document.getElementById("playBtn").style.pointerEvents = "none";
done

2022-05-18 07:30 UTC, vrezhMik commented on src/anim.js
>  let loopSys = async () => {
done

2022-05-18 07:42 UTC, vrezhMik commented on src/anim.js
> +let getLanguage = parseURLParams(window.location.href);
done

2022-05-18 07:47 UTC, vrezhMik commented on src/anim.js
> +  content = e["data"][getLanguage];
done

2022-05-18 07:51 UTC, vrezhMik commented on src/anim.js
> +  cont = canvas.getContext("2d");
done

2022-05-18 08:02 UTC, vrezhMik commented on src/anim.js
> +    nv;
I tried but i still had same amount of lines. I dont think there are a big difference

2022-05-18 08:05 UTC, vrezhMik commented on src/data_manager.js
> +    console.log(numArray);
done

2022-05-18 08:05 UTC, vrezhMik commented on src/examiner.js
> +    console.log(document.getElementById("answerBox"));
done

2022-05-18 08:16 UTC, vrezhMik commented on index.html
> +            <div class="exportButton" id="importBtn">
done

2022-05-18 08:17 UTC, vrezhMik commented on src/data_manager.js
> +  } else {
i changed the function

2022-05-18 08:19 UTC, vrezhMik commented on src/examiner.js
> +  if (answer[0]) {
that was for checking. Removed

2022-05-18 08:20 UTC, vrezhMik commented on src/anim.js
> +    await delay(37);
delay is a function which returns promise. That is not my function but i believe that we wait for return value

2022-05-18 08:21 UTC, vrezhMik commented on src/pluginAPI.js
> +        if (data === undefined) {
done

2022-05-18 08:21 UTC, vrezhMik commented on src/pluginAPI.js
> +        if (data.message !== undefined) {
done

2022-05-18 08:22 UTC, vrezhMik commented on src/ui_manager.js
> +  selectedFrames: [1, 8, 13, 18, 22, 25, 27, 29, 48],
I used them for check.

2022-05-18 08:22 UTC, vrezhMik commented on src/ui_manager.js
> +  selectedFrames: [1, 8, 13, 18, 22, 25, 27, 29, 48],
done

2022-05-18 08:22 UTC, vrezhMik commented on src/ui_manager.js
> +    document.getElementById("playBtn").style.pointerEvents = "none";
so buttons wont do anything

2022-05-18 08:23 UTC, vrezhMik commented on index.html
> +                <ul id="contentList"></ul>
I removed content list. content row just holds all content init

2022-05-18 08:24 UTC, vrezhMik commented on src/ui_manager.js
> +  presentData: function (content) {
done

2022-05-18 15:02 UTC, tumochristine requested changes

2022-05-19 07:52 UTC, vrezhMik commented on .vscode/settings.json
> +  "liveServer.settings.port": 5501
done

2022-05-19 07:59 UTC, vrezhMik commented on src/data_manager.js
> +    if (checkTheAnswer(UIManager.selectedFrames)) {
done

2022-05-19 07:59 UTC, vrezhMik commented on src/data_manager.js
> +      let selectedList = shuffle(UIManager.selectedFrames);
So that students will not share it together. Tatev told me to get different answers each time

2022-05-19 09:23 UTC, vrezhMik commented on src/anim.js
> +    nv;
done

2022-05-19 09:24 UTC, vrezhMik commented on src/anim.js
> +
done

2022-05-19 09:24 UTC, vrezhMik commented on src/anim.js
> +  return parms["lang"];
done

2022-05-19 09:25 UTC, vrezhMik commented on src/ui_manager.js
> +  return true;
done

2022-05-19 09:34 UTC, vrezhMik commented on src/ui_manager.js
> +  return true;
done

2022-05-19 09:34 UTC, vrezhMik commented on index.html
> +            <div id="infoCont">
done

2022-05-19 09:34 UTC, vrezhMik commented on index.html
> +                <div id="infoBtnRowBg"></div>
done

2022-05-19 09:35 UTC, vrezhMik commented on src/data_manager.js
> +var secondTimeKey = "";
todo added

2022-05-19 10:54 UTC, tumochristine approved these changes
LGTM Vrezh 👍  Once we talk to Tatev, we can decide how to go forward on the second and third info popup windows. Let's just commit those changes in a different pull request

2022-05-19 10:56 UTC, merged