Remove GET url for the tool to get lang.
Tumo-Product/timing-and-spacing pull request #19
Opened 2022-07-22 08:31 UTC by vrezhMikTumo

Tool used to determine language by GET url (?lang=<value>). PluginAPI returns lang set by editor which can be used. Remove languageFromURL function. Add initData object which keeps language init.

2022-07-22 10:02 UTC, HaykAvagyan1 requested changes
There is some minor changes to be done, also did you check if this works in the path? If not thoroughly test that it works with all languages and that the language codes are the same before merging (you might have let's say GE for German and in activity manager it might be DE or vice versa).

2022-07-22 12:53 UTC, vrezhMikTumo commented on src/anim.js
> +  let lang= await pluginAPI.initialize()
done

2022-07-22 12:53 UTC, vrezhMikTumo commented on src/anim.js
> +  content = getData;
done

2022-07-26 07:00 UTC, vrezhMikTumo commented on src/pluginAPI.js
> +    initData.value = false
done

2022-07-26 07:00 UTC, vrezhMikTumo commented on src/pluginAPI.js
> +        }initData.value = false;
done

2022-07-26 07:42 UTC, HaykAvagyan1 requested changes
Looks good, some very small changes. Did you test in path? Because I think the language code in activity-manager for Armenian is `hy` instead of `am` (please double check by looking at the `language` variable in the `init-response` or ask engineers).

2022-07-26 07:42 UTC, HaykAvagyan1 commented on src/anim.js
> +  const language = (await pluginAPI.initialize()).language
I think there should be a semicolon here for consistent code style.

2022-07-26 07:42 UTC, HaykAvagyan1 commented on src/examiner.js
> +  document.getElementById("answerBox").style.background = answer.answer_state
Semicolon missing

2022-07-26 07:42 UTC, HaykAvagyan1 commented on src/examiner.js
> +  console.log(answer.answer_state)
Remove log.

2022-07-26 08:57 UTC, vrezhMikTumo commented on src/examiner.js
> +  console.log(answer.answer_state)
done

2022-07-26 08:58 UTC, vrezhMikTumo commented on src/examiner.js
> +  document.getElementById("answerBox").style.background = answer.answer_state
done

2022-07-26 09:00 UTC, vrezhMikTumo commented on src/anim.js
> +  const language = (await pluginAPI.initialize()).language
done

2022-07-26 10:17 UTC, HaykAvagyan1 requested changes
Looks good, small thing that would be nice to have and then we can merge.

2022-07-26 10:17 UTC, HaykAvagyan1 commented on src/anim.js
> +  const language = (await pluginAPI.initialize()).language;
Can you make this `const language = (await pluginAPI.initialize()).language || "en";` so the default language is English if we try to use it outside of activity manager

2022-07-26 10:25 UTC, HaykAvagyan1 approved these changes
Nice!

2022-07-26 10:26 UTC, merged